language: ruby
rvm:
- 2.2.5
sudo: false
script: bundle exec rake deploy
env:
  global:
    - GH_REF: github.com/imbur/imbur.github.io
    - secure: NXBlv2pzXCsKUnsEzpTUJK7HgqVXVBGNXnIP4HMoFq9nHx5cFkXrqE3uyUUiw2zRSGecPDj4eZMfY/XPsv+TDPCb7yVwDzcUnkLT7OAqq8E8OewM15NrR6BbXusyT3p7gLxCq3WMny9AJ9Mg3DHZML1Pxj8M1robBV29IRVRNWw8yqEcAR0NIvIv/WFejzaD1UNlYxrSBiW/PYclJBgipXa5MYk20+3BAxpcNA0mRoVL5xcD+nSPBA1oIrTy26aAgE2pH0aC74hXFQu/mg2t8WEeOAQRcHuRMwCSKQ7JYcwa3SwdpPVTAOog25tZ5sgTHu7y9hqMgKBIOwSYkayd+sEukSehVDS1ZMlE20xEev/hr7sWwGhsmT3lRvQ0brWIFeS/eW5hrbTLwSIV1J9ymYsYF6p8jV70fqfNdASj8YZ/hOOROhDBHQDWILZNWctdwu9YQF9JVCS3xpQek4Y9HHiwgI9YFupH1mXY4Ton12Xe2U0KqLQYkTJmPnp3pAF/CXB6c1YTMb1V4jW27DRvfGC7nFFyNxhhhoGmiZbzDPV/NOkHLOH+pyyOzkvpI8tNe8UbTD4z/+apWwoCrsxraXU72sfQCNtkmLrwo+/wyO9+j3PDuOtcKgwJyBHc8w8Jt0fGIV9pYCJmjwosIZQoyOBijNA8n9DSO3Rnw3SENAM=
